"""initial schema

Revision ID: 3ac248e42e48
Revises: 
Create Date: 2026-05-18 11:13:55.884268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac248e42e48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('settings', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('file_format', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'artist', 'reviewer', 'viewer')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('parent_asset_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tags', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("asset_type IN ('model_3d', 'texture_2d', 'sprite', 'material', 'animation_clip', 'prefab', 'audio', 'vfx')", name='ck_assets_asset_type'),
    sa.CheckConstraint("source IN ('ai_generated', 'manual_upload', 'hybrid')", name='ck_assets_source'),
    sa.CheckConstraint("state IN ('draft', 'processing', 'review', 'approved', 'rejected', 'published', 'deprecated')", name='ck_assets_state'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_parent', 'assets', ['parent_asset_id'], unique=False)
    op.create_index('idx_assets_team_state', 'assets', ['team_id', 'state'], unique=False)
    op.create_table('asset_dependencies',
    sa.Column('dependent_asset_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_asset_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_type', sa.Text(), nullable=False),
    sa.CheckConstraint("dependency_type IN ('references_texture', 'references_material', 'references_rig', 'references_animation')", name='ck_asset_dependencies_type'),
    sa.ForeignKeyConstraint(['dependency_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dependent_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dependent_asset_id', 'dependency_asset_id', 'dependency_type')
    )
    op.create_table('asset_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('storage_key_thumbnail', sa.Text(), nullable=True),
    sa.Column('file_format', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'version', name='uq_asset_version')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('reference_image_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('total_stages', sa.Integer(), nullable=True),
    sa.Column('completed_stages', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'partial', 'failed')", name='ck_pipeline_runs_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'rejected', 'changes_requested')", name='ck_reviews_decision'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('processor_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('input_artifact_ids', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('output_artifact_ids', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('config', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'skipped')", name='ck_pipeline_steps_status'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_steps')
    op.drop_table('reviews')
    op.drop_table('pipeline_runs')
    op.drop_table('asset_versions')
    op.drop_table('asset_dependencies')
    op.drop_index('idx_assets_team_state', table_name='assets')
    op.drop_index('idx_assets_parent', table_name='assets')
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('artifacts')
    op.drop_table('teams')
    # ### end Alembic commands ###
