"""add_asset_version_links_and_status

Revision ID: b5ef56bb3a03
Revises: b2c3d4e5f6a7
Create Date: 2026-05-21 20:42:25.082224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ef56bb3a03'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_version_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_version_id', sa.Uuid(), nullable=False),
    sa.Column('to_version_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("link_type IN ('edited_from', 'replaces', 'imported_from')", name='ck_asset_version_links_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_version_id'], ['asset_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_version_id'], ['asset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('asset_versions', sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False))
    op.execute("UPDATE asset_versions SET status = 'active' WHERE status IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_versions', 'status')
    op.drop_table('asset_version_links')
    # ### end Alembic commands ###
